Update python-xarray to version 2026.02.0 / rev 57 via SR 1366375
https://build.opensuse.org/request/show/1366375
by user mcalabkova + dimstar_suse
- Add missing BuildRequires: python-pytz
 * xarray/tests/test_variable.py imports pytz directly since 2026.02.0,
   causing test collection errors on openSUSE_Tumbleweed x86_64:
   ModuleNotFoundError: No module named 'pytz'