Update apache2-mod_auth_openidc to version 2.4.17.1 / rev 39 via SR 1288215
https://build.opensuse.org/request/show/1288215
by user pgajdos + anag_factory
- version update to 2.4.17.1
  * fix usage of OIDCSessionType client-cookie:persistent:store_id_token; see #1331; thanks @rgcv
  * fix usage of OIDCPreservePostTemplates, regression in 2.4.17; see #1325; thanks @perry19987
  * javascript: use HTMLFormElement.prototype.submit.call(document.forms[0]) on all Javascript
    auto-submit POST forms to prevent browser Javascript error: "form.submit is not a function"
  * metrics: avoid possible segfault after restart twice; thanks @atzm
  * code: refactor util.c into util/ directory
  * allow adding a prefix to the cache (section) key through environment variable OIDC_CACHE_PREFIX