Update nethack to version 3.4.3 / rev 8 via SR 1291315
https://build.opensuse.org/request/show/1291315
by user tdz + anag_factory
Fixes to make NetHack build with gcc15:

- Add nethack-WINCHAIN-a-framework-allowing-multiple-processors-be.patch:
  Define preprocessor token UNUSED to mark unused variables. (boo#1245527)
- Add nethack-address-H4266-build-problem-with-clang-Modules.patch: Fix
  passing an incorrect function signature for signal handling.
  allmain.c: In function ‘newgame’:
  allmain.c:507:31: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  507 |         (void) signal(SIGINT, (SIG_RET_TYPE) done1);
      |                               ^~~~~~~~~~~~~~~~~~~~
      |                               |
      |                               void (*)(void)
  The patch from upstream changes a number of things for OSX support,
  but we only take the fixes to signa