Update python-httplib2 to version 0.22.0 / rev 54 via SR 1074515
https://build.opensuse.org/request/show/1074515
by user dirkmueller + dimstar_suse
- update to 0.22.0:
  * https: disable_ssl_certificate_validation caused
    ValueError: Cannot set verify_mode to CERT_NONE when
    check_hostname is enabled