Update python-kiwi to version 10.2.38 / rev 143 via SR 1329679
https://build.opensuse.org/request/show/1329679
by user marcus.schaefer + anag_factory
- Bump version: 10.2.37 → 10.2.38

- Fix booting non-encrypted live images
  activate_luks returned true if the passed blockdev was not luks.

- Fix pytest type hint issue
  Running on pytest < 7 causes an AttributeError:
  module 'pytest' has no attribute 'Config'. Quoting
  the type hint argument to be a string and accessing
  the elements of pytestconfig via getattr() and a
  default value workarounds the issue for older pytest
  versions

- Fix platform mock for kis builder unit testing

- Fix s390 unit test
  Forgot to mock the architecture properly. This commit fixes it