Update cppcheck to version 2.7.4 / rev 23 via SR 965031
https://build.opensuse.org/request/show/965031
by user dirkmueller + dimstar_suse
- update to 2.7.4:
  * Fixes "undefined reference to `tinyxml2::"
  * Replace tinyxml2_LIBRARY with tinyxml2_LIBRARIES