Update vlang to version 0.5.1 / rev 6 via SR 1364987
https://build.opensuse.org/request/show/1364987
by user VaiTon + dimstar_suse
- Require mbedtls-3-devel explicitly to fix compilation.
- Drop 0006-Use-private-mbedtls-headers.patch: this patch was
  originally added to attempt mbedtls 4.x compatibility but is
  incorrect and unnecessary since mbedtls 3.x uses the standard
  header paths (e.g. mbedtls/entropy.h).

- Use private mbedtls headers for compatibility with mbedtls 4.x
  via 0006-Use-private-mbedtls-headers.patch.
- Refresh all patches.

- Improve packaging:
  * Unbundle cJSON and zstd via 0003-Unbundle-cJSON-and-zstd.patch.
  * Fix undefined reference to cJSON_GetErrorPos when using system
    libcjson via 0004-Fix-cJSON_GetErrorPos-undefined-reference.patch.
  * Force use of system libgc on Linux via
    0005-Force-system-libgc-on-Linux.patch.
  * Enable vdoc by adding vlang/markdown as a dependency.
  * Im