Update s390-tools to version 2.34.0 / rev 80 via SR 1196040
https://build.opensuse.org/request/show/1196040
by user ngueorguiev + anag+factory
* Applied a patch to fix Rust compilation errors (bsc#1229461)
  - s390-tools-2.34-Fix-Rust-compilation-errors.patch
  - Fix: s390-tools: Rust compilation errors (s390_pv_core), build fails with
    "error: unnecessary qualification"
* Added BuildRequieres in the .spec file
  - perl-Bootloader >= 0.4.15
* Upgrade s390-tools to version 2.34 (jsc#PED-3223,jsc#PED-9591)
*** v2.34.0
* Changes of existing tools:
  - ap_tools/ap-check: Add support for vfio-ap dynamic configuration
  - dbginfo.sh: Update/Add additional DASD data collection
  - dumpconf: Add new parameter 'SCP_DATA' for SCSI/NVMe/ECKD dump devices
  - libutil: Make formatted meta-data configurable
  - s390-tools: Replace 'which' with built-in 'command -v'
  - zdump/dfi_elf: Support core dumps of vr-kernels
* Bug Fixes:
  - chzdev: