Update lsdvd to version 0.20 / rev 3 via SR 1312144
https://build.opensuse.org/request/show/1312144
by user alois + dimstar_suse
- Fix patch fix-input-XML_DEPRECATED_MEMBER.patch:
  The former causes a segfault in testsuite/output-xml
- Add the section %check. Due to the packages required for this,
  the tests are disabled and can be run locally, e.g., with
  'osc build openSUSE_Tumbleweed x86_64 lsdvd.spec --with tests'
- Add fix-input-XML_DEPRECATED_MEMBER.patch
  * fixes 'error: called object is not a function or function pointer'
    'ret = handler->input(out, &out_size, (const xmlChar *) in, &temp)'
    in oxml.c for libxml2 >= 2.14.5