Update python-zeroconf to version 0.28.6 / rev 16 via SR 850926
https://build.opensuse.org/request/show/850926
by user dirkmueller + dimstar_suse
- update to 0.28.6:
  * Loosened service name validation when receiving from the network this lets us handle
  some real world devices previously causing errors
  * Enabled ignoring duplicated messages which decreases CPU usage
  * Fixed spurious AttributeError: module 'unittest' has no attribute 'mock'
  * Improved cache reaper performance significantly