Update python-canonicaljson to version 1.4.0 / rev 8 via SR 889399
https://build.opensuse.org/request/show/889399
by user okurz + dimstar_suse
Exclude tests on older SLE+Leap due to "ImportError: cannot import name inf"